#!/usr/bin/bash

# Hard coded file path is bad :(
## TODO: To be fixed
ICON='/usr/share/icons/Adwaita/64x64/status/network-offline-symbolic.symbolic.png'

## $1 = Title, $2 = message
notify() {
    notify-send --app-name=MBSYNC --urgency=critical --icon="$ICON" "Error retrieving mails of $1" "$2"
}

## $1 = .isync mail entry, $2 = mail address for notification
syncmail() {
    echo "Syncing $2"
    ## See https://unix.stackexchange.com/a/474195
    { err=$(mbsync --config "${HOME}/.isyncrc" "$1" 2>&1 >&3 3>&-); } 3>&1
    [ "" == "$err" ] || notify "$2" "$err"
    err=''
}

## Move mails depending of previous notmuch tags.
"$HOME/bin/notmuch-tag-move.sh"

syncmail 'ivaldime' 'ivaldi.me'
syncmail 'acmontpellier' 'ac-montpellier.fr'
syncmail 'ovyafr' 'ovya.fr'
